### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by catt-wuyang** [vv314/wintip#1]
When I run `npm run build` to create dist file, the error occurred:
```
node v7.7.2
```

```
➜  wintip git:(master) ✗ npm run build

> wintip@1.1.3 build /Users/muzidx/wintip
> rimraf dist && cross-env NODE_ENV=prod node build/scripts

TypeError: util.promisify is not a function
    at write (/Users/muzidx/wintip/build/utils.js:8:26)
    at build (/Users/muzidx/wintip/build/scripts.js:54:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

**Comment by catt-wuyang** [comment]
wow, I google `util`  npm package, util has not util.promisify function, need to npm install util.promisify?

**Comment by vv314** [comment]
require node 8.0+

```
"engines": {
    "node": ">=8.0.0"
  }
```

`build/script.js` used `util.promisify` method and async function in node v8.0
